services:
  niblette:
    image: niblette-server:0.1
    restart: unless-stopped
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/database:/var/lib/postgresql/data/pgdata
      - ./postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DB_PW}