version: '3.3'

services:
  niblette:
    image: niblette:0.1
    restart: unless-stopped
    environment:
      DATABASE: 192.168.1.20

  db:
    image: mariadb:latest
    command: --max_allowed_packet=536870912
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: sf87h
      MARIADB_DATABASE: niblette